version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: book_review_postgres
    environment:
      POSTGRES_USER: book_review_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: book_review_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - book_review_network

volumes:
  postgres_data:

networks:
  book_review_network:
    driver: bridge
